# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=b'', max_length=200)),
                ('Subject', models.CharField(default=b'', max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('From', models.CharField(choices=[(b'00:00', b'00:00'), (b'00:15', b'00:15'), (b'00:30', b'00:30'), (b'00:45', b'00:45'), (b'00:60', b'00:60'), (b'01:00', b'01:00'), (b'01:15', b'01:15')], default=b'', max_length=60, unique=True)),
                ('to', models.CharField(choices=[(b'00:00', b'00:00'), (b'00:15', b'00:15'), (b'00:30', b'00:30'), (b'00:45', b'00:45'), (b'00:60', b'00:60'), (b'01:00', b'01:00'), (b'01:15', b'01:15')], default=b'', max_length=60, unique=True)),
                ('instructor', models.CharField(default=b'', max_length=60)),
                ('description', models.TextField(default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
