# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_createclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclass',
            name='From',
            field=models.CharField(choices=[(b'00:00', b'00:00'), (b'00:15', b'00:15'), (b'00:30', b'00:30'), (b'00:45', b'00:45'), (b'00:60', b'00:60'), (b'01:00', b'01:00'), (b'01:15', b'01:15')], default=b'', max_length=60),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='to',
            field=models.CharField(choices=[(b'00:00', b'00:00'), (b'00:15', b'00:15'), (b'00:30', b'00:30'), (b'00:45', b'00:45'), (b'00:60', b'00:60'), (b'01:00', b'01:00'), (b'01:15', b'01:15')], default=b'', max_length=60),
        ),
    ]
