# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170726_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclass',
            name='From',
            field=models.CharField(choices=[(b'01:00', b'01:00'), (b'02:00', b'02:00'), (b'03:00', b'03:00'), (b'04:15', b'04:00'), (b'05:00', b'05:00'), (b'06:00', b'06:00'), (b'07:00', b'07:00'), (b'08:00', b'08:00'), (b'09:00', b'09:00'), (b'10:15', b'10:00'), (b'11:00', b'11:00'), (b'12:00', b'12:00')], default=b'', max_length=60),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='to',
            field=models.CharField(choices=[(b'01:00', b'01:00'), (b'02:00', b'02:00'), (b'03:00', b'03:00'), (b'04:15', b'04:00'), (b'05:00', b'05:00'), (b'06:00', b'06:00'), (b'07:00', b'07:00'), (b'08:00', b'08:00'), (b'09:00', b'09:00'), (b'10:15', b'10:00'), (b'11:00', b'11:00'), (b'12:00', b'12:00')], default=b'', max_length=60),
        ),
    ]
