# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170726_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclass',
            name='date',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
