# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20170727_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='createclass',
            name='From',
            field=models.CharField(choices=[(b'01:00 am', b'01:00 am'), (b'02:00 am', b'02:00 am'), (b'03:00 am', b'03:00 am'), (b'04:15 am', b'04:00 am'), (b'05:00 am', b'05:00 am'), (b'06:00 am', b'06:00 am'), (b'07:00 am', b'07:00 am'), (b'08:00 am', b'08:00 am'), (b'09:00 am', b'09:00 am'), (b'10:00 am', b'10:00 am'), (b'11:00 am', b'11:00 am'), (b'12:00 am', b'12:00 am'), (b'01:00 pm', b'01:00 pm'), (b'02:00 pm', b'02:00 pm'), (b'03:00 pm', b'03:00 pm'), (b'04:00 pm', b'04:00 pm'), (b'05:00 pm', b'05:00 pm'), (b'06:00 pm', b'06:00 pm'), (b'07:00 pm', b'07:00 pm'), (b'08:00 pm', b'08:00 pm'), (b'09:00 pm', b'09:00 pm'), (b'10:15 pm', b'10:00 pm'), (b'11:00 pm', b'11:00 pm'), (b'12:00 pm', b'12:00 pm')], default=b'', max_length=60),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='to',
            field=models.CharField(choices=[(b'01:00 am', b'01:00 am'), (b'02:00 am', b'02:00 am'), (b'03:00 am', b'03:00 am'), (b'04:15 am', b'04:00 am'), (b'05:00 am', b'05:00 am'), (b'06:00 am', b'06:00 am'), (b'07:00 am', b'07:00 am'), (b'08:00 am', b'08:00 am'), (b'09:00 am', b'09:00 am'), (b'10:00 am', b'10:00 am'), (b'11:00 am', b'11:00 am'), (b'12:00 am', b'12:00 am'), (b'01:00 pm', b'01:00 pm'), (b'02:00 pm', b'02:00 pm'), (b'03:00 pm', b'03:00 pm'), (b'04:00 pm', b'04:00 pm'), (b'05:00 pm', b'05:00 pm'), (b'06:00 pm', b'06:00 pm'), (b'07:00 pm', b'07:00 pm'), (b'08:00 pm', b'08:00 pm'), (b'09:00 pm', b'09:00 pm'), (b'10:15 pm', b'10:00 pm'), (b'11:00 pm', b'11:00 pm'), (b'12:00 pm', b'12:00 pm')], default=b'', max_length=60),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Createclass'),
        ),
    ]
