# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20170731_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='lecture',
        ),
    ]
