# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='chater',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
