# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.AddField(
            model_name='createclass',
            name='chater',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
