# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20170801_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createclass',
            name='chater',
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default=b'jatinder', max_length=200),
        ),
    ]
