# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20170801_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Image',
            field=models.CharField(max_length=200),
        ),
    ]
