# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20170802_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Image',
            field=models.ImageField(blank=True, upload_to=b'profile_image'),
        ),
    ]
