# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20170802_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Image',
            field=models.ImageField(blank=True, default=b'http://static-23.sinclairstoryline.com/resources/media/d368a1cb-f6af-4a04-83d0-ebc66e984ab2-large16x9_BIOPIC.jpg', upload_to=b'profile_image'),
        ),
    ]
