# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20170803_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Image',
            field=models.ImageField(blank=True, upload_to=b'profile_image'),
        ),
    ]
