# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:41
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20170803_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='createclass',
            name='student',
            field=models.CharField(default=b'', max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
    ]
