# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_remove_createclass_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclass',
            name='date',
            field=models.DateField(default=b'', max_length=200),
        ),
    ]
