# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_auto_20170818_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(default=b'1', max_length=20),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='From',
            field=models.CharField(default=b'', max_length=60),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='to',
            field=models.CharField(default=b'', max_length=60),
        ),
    ]
