# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_auto_20170823_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='status',
        ),
    ]
