# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_remove_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclass',
            name='date',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
